### ISSUE TITLE
Meta viewport code not working on phone

### ISSUE THREAD

**Issue by jerrygraced** [jerrygraced/flabby-birds#3]
@cbas when I used the meta viewport code `<meta name="viewport" content="width=device-width, initial-scale=1"> ` on my index.html and viewed the website on my phone, I wasn't able to zoom out anymore.  

Is there a way to enable zooming out?  Or better still, be able to customize the zoom-level to make it more optimal and fit all elements onto device screen.  I tried playing with the `initial-scale` value but didn't seem to make a difference.

**Comment by cbas** [comment]
@jerrygraced Requiring users to zoom out and having all elements fit on screen are fundamentally opposed in most cases. Especially for a game you probably want to make sure all necessary controls are on the screen.

**Comment by jerrygraced** [comment]
@cbas Yes makes sense.  Fixed this by using a combination of meta viewport and media queries via commits [#c31fb5f](https://github.com/jerrygraced/flabby-birds/commit/c31fb5f3158c364f70d88860dd7a1ccb1388f61b) and [#691563](https://github.com/jerrygraced/flabby-birds/commit/691563ef4a78cc56e61c313b2d983e6a26af53ce).  Closing issue now, thanks!

**Comment by cbas** [comment]
:+1: Nice work!
